import { _electron as electron, expect, test } from '@playwright/test'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { SqliteStore } from '../../src/main/db/store'

const environment = (directory: string) => ({
  ...process.env, SPLITTBOT_DATA_DIR: directory, SPLITTBOT_TEST_MODE: '1', SPLITTBOT_DEFAULT_CWD: process.cwd(),
  SPLITTBOT_CODEX_COMMAND: process.execPath, SPLITTBOT_CODEX_ARGS_JSON: JSON.stringify([resolve('tests/fixtures/fake-app-server.mjs')])
})

test('Home shortcuts work with zero counts, support keyboard access, and starters only draft', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'splittbot-navigation-empty-'))
  const application = await electron.launch({ args: [resolve('out/main/index.js')], env: environment(directory) })
  try {
    const page = await application.firstWindow()
    await expect(page.getByText('Good to see you.')).toBeVisible()
    const work = page.getByRole('button', { name: 'Working now: 0. View current work' })
    await work.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'Working now', exact: true })).toBeVisible()
    await expect(page.getByText('No work is running', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open agents', exact: true }).click()
    await expect(page.getByLabel('Message Atlas')).toBeVisible()
    const starter = page.getByRole('button', { name: 'Plan the next three actions', exact: true })
    await starter.click()
    await expect(page.getByLabel('Message Atlas')).toHaveValue('Plan the next three actions')
    await expect(page.getByLabel('Message Atlas')).toBeFocused()
    await page.getByLabel('Message Atlas').fill('My existing draft')
    await starter.click()
    await expect(page.getByLabel('Message Atlas')).toHaveValue('My existing draft\n\nPlan the next three actions')
    expect(await page.evaluate(async () => (await window.splittbot.bootstrap()).runs.length)).toBe(0)
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Needs attention: 0. Open your action queue' }).click()
    await expect(page.getByRole('heading', { name: 'Your queue is clear' })).toBeVisible()
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Need approval: 0. Review pending requests' }).click()
    await expect(page.getByText('Nothing is waiting', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Pending requests' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Active agents: 1. Open your team' }).click()
    await expect(page.getByLabel('Message Atlas')).toHaveValue('My existing draft\n\nPlan the next three actions')
    await page.getByRole('button', { name: 'Add a schedule', exact: true }).click()
    await expect(page.locator('.agent-modal')).toBeVisible()
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.getByLabel('Home', { exact: true }).click()
    const session = await page.context().newCDPSession(page)
    await session.send('Emulation.setDeviceMetricsOverride', { width: 900, height: 640, deviceScaleFactor: 1, mobile: false })
    expect(await page.locator('.metric').evaluateAll((cards) => cards.every((card) => card.scrollWidth <= card.clientWidth))).toBe(true)
    await page.screenshot({ path: test.info().outputPath('home-shortcuts-compact.png') })
    await page.evaluate(async () => { const snapshot = await window.splittbot.bootstrap(); await window.splittbot.agents.archive(snapshot.agents[0]!.id) })
    await page.getByRole('button', { name: 'Active agents: 0. Create an agent' }).click()
    await expect(page.getByRole('heading', { name: 'Create an agent', exact: true })).toBeVisible()
  } finally { await application.close() }
})

test('Home cards, history, actions, notifications, and artifacts open exact work without starting tasks', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'splittbot-navigation-records-'))
  const store = await SqliteStore.open(join(directory, 'splittbot.sqlite'))
  await store.ensureSeedAgent(process.cwd())
  const agent = store.listAgents()[0]!
  const oldRun = await store.createRun(agent.id, 'Older planning result')
  await store.updateRun(oldRun.id, { status: 'completed', output: 'Older result retained beyond the recent-history window.', completedAt: new Date().toISOString() })
  for (let i = 0; i < 104; i++) {
    const run = await store.createRun(agent.id, `Sample completed request ${i}`)
    await store.updateRun(run.id, { status: 'completed', output: `Sample result ${i}`, completedAt: new Date().toISOString() })
  }
  const recent = await store.createRun(agent.id, 'Newest launch review')
  await store.updateRun(recent.id, { status: 'completed', output: 'Full launch review\n' + 'Evidence and next steps. '.repeat(150) + '\nEND OF RESULT', completedAt: new Date().toISOString() })
  await store.createArtifact({ agentId: agent.id, runId: oldRun.id, name: 'Complete planning notes', content: 'Saved notes. '.repeat(100) + 'END OF SAVED NOTES' })
  await store.createNotification({ type: 'routineCompleted', title: 'Planning review ready', body: 'Open the retained planning result.', agentId: agent.id, runId: oldRun.id })
  await store.flush()
  store.close()
  const application = await electron.launch({ args: [resolve('out/main/index.js')], env: environment(directory) })
  try {
    const page = await application.firstWindow()
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await expect(page.getByText('Good to see you.')).toBeVisible()
    const ids = await page.evaluate(async ({ agentId, oldRunId }) => {
      const first = await window.splittbot.actions.create({ title: 'Choose the first plan', summary: 'Compare the two proposed plans.', type: 'decision', priority: 'normal', sourceAgentId: agentId })
      const second = await window.splittbot.actions.create({ title: 'Review the older planning result', summary: 'Use the retained planning notes to decide the next step.', type: 'task', priority: 'normal', sourceAgentId: agentId, sourceRunId: oldRunId, dueAt: new Date(Date.now() + 60_000).toISOString() })
      const waiting = await window.splittbot.actions.create({ title: 'Waiting for a response', summary: 'Follow up when the response arrives.', type: 'followUp', priority: 'normal', sourceAgentId: agentId })
      await window.splittbot.actions.update(waiting.id, { status: 'waiting' })
      return { first: first.id, second: second.id }
    }, { agentId: agent.id, oldRunId: oldRun.id })
    await page.getByRole('button', { name: 'Open action: Review the older planning result', exact: true }).click()
    await expect(page.locator('.action-detail h3')).toHaveText('Review the older planning result')
    await page.getByRole('button', { name: 'View source run', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Run details' })).toContainText('Older result retained beyond the recent-history window.')
    expect(await page.evaluate(async (id) => (await window.splittbot.bootstrap()).runs.some((run) => run.id === id), oldRun.id)).toBe(false)
    expect(await page.evaluate(async () => { try { await window.splittbot.runs.get('../bad-id'); return false } catch { return true } })).toBe(true)
    await page.getByRole('button', { name: 'View captured actions' }).click()
    await expect(page.locator('.action-list .action-card')).toHaveCount(1)
    await expect(page.locator('.action-detail h3')).toHaveText('Review the older planning result')
    await page.getByRole('button', { name: 'Show due soon actions: 1' }).click()
    await expect(page.locator('.action-list .action-card')).toHaveCount(1)
    await page.getByRole('button', { name: 'Show decisions actions: 1' }).click()
    await expect(page.locator('.action-detail h3')).toHaveText('Choose the first plan')
    await page.getByRole('button', { name: 'Show waiting actions: 1' }).click()
    await expect(page.locator('.action-detail h3')).toHaveText('Waiting for a response')
    await page.getByLabel('Find an action').fill('No such item')
    await expect(page.locator('.action-detail')).toHaveCount(0)
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Open completed run: Newest launch review', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Run details' })).toContainText('END OF RESULT')
    await page.screenshot({ path: test.info().outputPath('run-details.png') })
    await page.getByLabel('Artifacts', { exact: true }).click()
    await page.getByRole('button', { name: 'Read output: Complete planning notes' }).click()
    await expect(page.getByRole('region', { name: 'Saved output' })).toContainText('END OF SAVED NOTES')
    await page.getByRole('button', { name: 'View source run', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Run details' })).toContainText('Older result retained beyond the recent-history window.')
    await page.getByLabel('Notifications', { exact: true }).click()
    await page.getByRole('button', { name: 'View run', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Run details' })).toContainText('Older result retained beyond the recent-history window.')
    expect(await page.evaluate(async () => (await window.splittbot.bootstrap()).notifications[0]!.read)).toBe(true)
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Active agents: 1. Open your team' }).click()
    await page.getByLabel('Message Atlas').fill('REQUEST_APPROVAL')
    await page.getByLabel('Send', { exact: true }).click()
    await expect.poll(async () => page.evaluate(async () => (await window.splittbot.bootstrap()).approvals.filter((approval) => approval.status === 'pending').length)).toBe(1)
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Working now: 1. View current work' }).click()
    await expect(page.locator('.run-row')).toHaveCount(1)
    await page.getByRole('button', { name: 'Open run: REQUEST_APPROVAL', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Run details' })).toContainText('Needs approval')
    await page.getByRole('region', { name: 'Run details' }).getByRole('button', { name: 'Review pending approvals' }).click()
    await expect(page.locator('.approval-card.pending')).toHaveCount(1)
    await page.getByRole('button', { name: 'Decline', exact: true }).click()
    await expect(page.getByText('Nothing is waiting', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'View approval history' }).click()
    await expect(page.locator('.approval-card.declined')).toHaveCount(1)
    await page.getByLabel('Home', { exact: true }).click()
    await page.getByRole('button', { name: 'Need approval: 0. Review pending requests' }).click()
    await expect(page.locator('.approval-card')).toHaveCount(0)
    expect(ids.first).not.toBe(ids.second)
    expect(errors).toEqual([])
  } finally { await application.close() }
})
